const assert = require('node:assert/strict');
require('./backup.js');
const { validate, merge } = globalThis.periodBackup;
const log = { flow: '中', note: '原有備註', symptoms: ['腹痛'], sex: true };
const original = { periods: [{ start: '2026-07-07', end: '2026-07-12' }], logs: { '2026-07-07': log } };
const snapshot = JSON.stringify(original);
const backup = { app: 'period-tracker', version: 1, state: original, ui: { pendingStart: '2026-09-09' } };
assert.deepEqual(validate(JSON.parse(JSON.stringify(backup))), backup);
assert.deepEqual(merge(original, original), original);
const additional = { periods: [{ start: '2026-08-09', end: '2026-08-14' }], logs: { '2026-08-09': log } };
assert.equal(merge(original, additional).periods.length, 2);
assert.equal(Object.keys(merge(original, additional).logs).length, 2);
assert.throws(() => merge(original, { periods: [{ start: '2026-07-07', end: '2026-07-13' }], logs: {} }));
assert.throws(() => merge(original, { periods: [], logs: { '2026-07-07': { ...log, note: '不同備註' } } }));
assert.throws(() => validate({ ...backup, ui: { pendingStart: '2026-02-30' } }));
assert.throws(() => validate({ ...backup, state: { periods: [{ start: '2026-02-30', end: '2026-03-01' }], logs: {} } }));
assert.throws(() => validate({ ...backup, state: { periods: [], logs: { '2026-07-07': null } } }));
assert.equal(JSON.stringify(original), snapshot);
console.log('Backup round-trip, merging, duplicate import, conflicts, invalid dates and original preservation passed.');
